import { Inter } from "next/font/google";
import type { Metadata } from "next";
import localFont from "@next/font/local";

import "./globals.css";

const univers = localFont({
  src: [
    {
      path: "../public/fonts/Univers-Light.woff2",
      weight: "200",
    },
    {
      path: "../public/fonts/Univers.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Univers-Bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-univers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={univers.className}>{children}</body>
    </html>
  );
}
